### ISSUE TITLE
Test-DSCConfiguration fails with EXOAcceptedDomain

### ISSUE THREAD

**Issue by ararag** [microsoft/Microsoft365DSC#1096]
Running Test-DSCConfiguration fails on EXOAcceptedDomain. 

**Error logged:** 
Event ID 4252:
MIResult: 1
Error Message: PowerShell DSC resource MSFT_EXOAcceptedDomain  failed to execute Test-TargetResource functionality with error message: Cannot retrieve the dynamic parameters for the cmdlet. Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method named 'IsCloudShellEnvironment'. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI

Event ID: 4250:
Message Cannot retrieve the dynamic parameters for the cmdlet. Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method named 'IsCloudShellEnvironment'. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

**Comment by ararag** [comment]
Can't reproduce this anymose, so closing.
