### ISSUE TITLE
EXO: Unable to run EXO Export Error Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method named 'IsCloudShellEnvironment'

### ISSUE THREAD

**Issue by aflopex** [microsoft/Microsoft365DSC#1118]
#### Details of the scenario you tried and the problem that is occurring
I get a failure and an error when executing the following command to export EXO configuration. This started happening suddenly after it several exports using the same command were successful

![image](https://user-images.githubusercontent.com/50927492/112186405-7b6e7c80-8bd7-11eb-9abf-c925fe44c39c.png)

#### Verbose logs showing the problem

[2021/03/23 11:52:53]
{InvalidArgument}
System.Management.Automation.ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method named 'IsCloudShellEnvironment'. ---> System.Management.Automation.RuntimeException: Method invocation failed because [Microsoft.Exchange.Management.AdminApiProvider.Utility] does not contain a method named 'IsCloudShellEnvironment'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.GetDynamicParameters()
   at System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(ParameterBindingException& outgoingBindingException)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Could not initiate the ReverseDSC Extraction"
at Connect-MSCloudLoginExchangeOnline, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.50\Workloads\ExchangeOnline.psm1: line 124
at Test-MSCloudLogin, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.50\MSCloudLoginAssistant.psm1: line 117
at New-M365DSCConnection, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\modules\M365DSCUtil.psm1: line 1095
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\DSCResources\MSFT_EXOAcceptedDomain\MSFT_EXOAcceptedDomain.psm1: line 375
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\modules\M365DSCReverse.psm1: line 501
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\modules\M365DSCReverseGUI.psm1: line 821
at Show-M365DSCGUI, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\modules\M365DSCReverseGUI.psm1: line 881
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1223.1\modules\M365DSCUtil.psm1: line 859
at <ScriptBlock>, <No file>: line 1

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
![image](https://user-images.githubusercontent.com/50927492/112186873-eddf5c80-8bd7-11eb-9a08-55bd090832b1.png)

![image](https://user-images.githubusercontent.com/50927492/112186892-f2a41080-8bd7-11eb-864f-4dbd4eb496d7.png)

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.4283.amd64fre.rs1_release.210303-1802
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Comment by aflopex** [comment]
Hello, anyone has seen this? or have any advice? The EXO export works fine using the GUI but not running the PS command. I have already tried different tenants and different accounts with the same result. Thank you

**Comment by NikCharlebois** [comment]
@aflopex sorry for the delay. Are you able to reproduce with the latest versions (not the dev branch)?  Thanks
