### ISSUE TITLE
Cannot call a method

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1123]
#### Details of the scenario you tried and the problem that is occurring
I tried to run Export-M365DSCConfiguration -Path "C:\temp\config\" -Workloads @("SC") -Quiet and I get
Add-M365DSCTelemetryEvent: C:\Users\dgross\OneDrive - Insight\Documents\PowerShell\Modules\Microsoft365DSC\1.21.317.1\modules\M365DSCUtil.psm1:849:5
Line |
 849 |      Add-M365DSCTelemetryEvent -Data $data
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

#### Verbose logs showing the problem
Error Acquiring Token:
System.Exception: AADSTS90010: The grant type is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint you used common.
Mitigation: as explained in the message from Azure AD, the authority you use in the application needs to be tenanted or otherwise organizations. change the "Tenant": property in the appsettings.json to be a GUID (tenant 
Id), or domain name (contoso.com) if such a domain is registered with your tenantor "organizations", if you want this application to sign-in users in any Work and School accounts.
InnerException : AADSTS900144: The request body must contain the following parameter: 'password'.
Trace ID: ac87f07d-fd65-4a24-8829-c8c725bd8e00
Correlation ID: 118e66e0-594a-4a19-ac93-9e57ed2ced6c
Timestamp: 2021-03-26 09:05:37Z
 ---> MSAL.NetCore.4.23.0.0.MsalServiceException:
        ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS900144: The request body must contain the following parameter: 'password'.
Trace ID: ac87f07d-fd65-4a24-8829-c8c725bd8e00
Correlation ID: 118e66e0-594a-4a19-ac93-9e57ed2ced6c
Timestamp: 2021-03-26 09:05:37Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken 
cancellationToken)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.GetTokenForWebApiUsingUsernamePasswordAsync(IEnumerable`1 scopes, String username, SecureString password)
        StatusCode: 400
        ResponseBody: {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'password'.\r\nTrace ID: ac87f07d-fd65-4a24-8829-c8c725bd8e00\r\nCorrelation ID: 
118e66e0-594a-4a19-ac93-9e57ed2ced6c\r\nTimestamp: 2021-03-26 09:05:37Z","error_codes":[900144],"timestamp":"2021-03-26 09:05:37Z","trace_id":"ac87f07d-fd65-4a24-8829-c8c725bd8e00","correlation_id":"118e66e0-594a-4a19-ac93-9e57ed2ced6c","error_uri":"https://login.microsoftonline.com/error?code=900144"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 118e66e0-594a-4a19-ac93-9e57ed2ced6c
x-ms-request-id: ac87f07d-fd65-4a24-8829-c8c725bd8e00
x-ms-ests-server: 2.1.11562.10 - EUS ProdSlices
x-ms-clitelem: 1,900144,0,,
Set-Cookie: fpc=AjBhkkBa6KtNoRrG8Zr3A70; expires=Sun, 25-Apr-2021 09:05:37 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Fri, 26 Mar 2021 09:05:36 GMT

   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.GetTokenForWebApiUsingUsernamePasswordAsync(IEnumerable`1 scopes, String username, SecureString password)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.GetAccessTokenAsync(String claims)
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.224.1

**Comment by DeanGross** [comment]
Never mind, I updated the module and this error is no longer occuring
