### ISSUE TITLE
AADGroup module issue - unable to run due to error

### ISSUE THREAD

**Issue by myacaman** [microsoft/Microsoft365DSC#1702]
#### Details of the scenario you tried and the problem that is occurring
I am getting the following error when I try to run the AADGroup resource.

#### Verbose logs showing the problem
System.Management.Automation.MethodInvocationException: Exception calling "SourceExists" with "1" argument(s): "The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security." ---> System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at CallSite.Target(Closure , CallSite , Type , String )

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Is this error happening when trying to configure the tenant with Start-DSCConfiguration or when you are trying to export a given AAD resource?

**Comment by myacaman** [comment]
I am running the command below. It runs and goes all the way to group 1,000
something out of 3,000 and then it throws an error. It stops everytime when
reading the exact same group. I can run the conditional access one without
a problem.
Export-M365DSCConfiguration -Components @(“AADGroup").

Best Regards,
Maria Y.

**Comment by SebastianGoers** [comment]
Hi @myacaman , do you have administrative privileges on your machine? I believe this error occurs when you are running into an issue during the export and the script fails to access the security section in the Windows event logs. There should be an alternative error log instead. Try finding a file similar to 12960-M365DSC-ErrorLog.log . As a side note: the actual issue with the group where the dsc export is failing should be in the file as well. You will find it right below the error message that you were posting.

**Comment by SebastianGoers** [comment]
Solution could be to run Powershell as administrator or disregard the issue and look for the actual issue in the error log mentioned in my previous post.

**Comment by myacaman** [comment]
Thank you Sebastian. I do have full admin privileges. I was able to look deeper into the logs and I am seeing an error regarding the group that is failing to be read because the display name value is null. I would think that it can read it and just display a blank value for the attribute, but it does not seem to be the case. Have you seen a similar experience?
