### ISSUE TITLE
Add-M365DSCEvent causes issues in non elevated PowerShell sessions

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2343]
#### Details of the scenario you tried and the problem that is occurring

Running M365DSC in a not elevated PowerShell Sesisons causes errors due to insufficient access rights to Event Log resources.

#### Verbose logs showing the problem

System.Management.Automation.MethodInvocationException: Exception calling "SourceExists" with "1" argument(s): "The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security." ---> System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at CallSite.Target(Closure , CallSite , Type , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Could not write to event log Source {MSFT_AADServicePrincipal} EntryType {Warning} Message {<M365DSCEvent>

#### Suggested solution to the issue

![image](https://user-images.githubusercontent.com/15608729/192728741-5f3148bc-8734-49af-9610-be44401d84f5.png)
Add the check, if session is elevated.

#### related issues

- #2334 
- #1702

**Comment by andikrueger** [comment]
This should be fixed in 1.22.1019.1. #2405
