### ISSUE TITLE
Instructions for GCC High tenant usage

### ISSUE THREAD

**Issue by tehmichael** [microsoft/Microsoft365DSC#2507]
Hello!

Love the tool and I understand how it works with commercial tenants but I'm not certain what adjustments that need to be made to interact with Government endpoints.  There doesn't seem to be any instructions detailing this process either (or at least I couldn't find any).  Would someone be able to help me please?  Thank you!

**Comment by desmay** [comment]
@tehmichael The authentication module should handle all the Gov cloud endpoints so there is nothing special that needs to be done running against a commercial vs gov cloud

**Comment by tehmichael** [comment]
@desmay - appreciate your quick response!  Are some workflows not supported in GCC High then?  I'm seeing this error when attempting to connect to SC workflow (AAD/Intune seem to work fine):

Connecting to {SecurityComplianceCenter}...Error Acquiring Token:
System.ArgumentException: The user is not recognized as a managed user, or a federated user.Azure AD was not able to identify the IdP that needs to process the user U/P: Wrong username ---> Microsoft.Identity.Client.MsalClientException: Unsupported User Type 'Unknown'. Please see https://aka.ms/msal-net-up.
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.<FetchAssertionFromWsTrustAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetTokenForWebApiUsingUsernamePasswordAsync>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetTokenForWebApiUsingUsernamePasswordAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetAccessTokenAsync>d__29.MoveNext()
❌
Connecting to remote server ps.compliance.protection.outlook.com failed with the following error message : ᗀuɚ For more information, see the about_Remote_Troubleshooting Help topic.

During the error I'll see a prompt for the account password, but it still seems to fail.

Let me know if any additional information is needed.  Thanks!

**Comment by desmay** [comment]
This should work let me see if team can repro

**Comment by tehmichael** [comment]
@NikCharlebois 

Its strange, if I try to export using `Export-M365DSCConfiguration -Path .\ -FileName helloworld_aad-int-sc2.ps1 -ConfigurationName helloworld_aad-int-sc2.ps1 -Workloads AAD,INTUNE,SC -Mode Full -Credential $creds`, I'll see the error reported above and in the same script window if I try the Connect-M365Tenant cmdlet like you asked I see this output:
```
Connect-M365Tenant -Credential $creds -Workload ExchangeOnline
UnAuthorized
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.0.0\netFramework\ExchangeOnlineManagement.psm1:730 char:21
+                     throw $_.Exception;
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], UnauthorizedAccessException
    + FullyQualifiedErrorId : UnAuthorized
```

But if I run the Connect-M365Tenant cmdlet in a new PowerShell window without trying the export first I don't see any output.

I did some additional digging and noticed that I'll see the same error as above if I try `Connect-ExchangeOnline -Credential $creds` directly after the export cmdlet:
```
Connect-ExchangeOnline -Credential $creds
UnAuthorized
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.0.0\netFramework\ExchangeOnlineManagement.psm1:730 char:21
+                     throw $_.Exception;
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], UnauthorizedAccessException
    + FullyQualifiedErrorId : UnAuthorized
```

But if I change the EchangeEnvironmentName to O365USGovGCCHigh, then things seem to proceed without issue:
```
Connect-ExchangeOnline -Credential $creds -ExchangeEnvironmentName O365USGovGCCHigh


----------------------------------------------------------------------------------------
This V3 EXO PowerShell module contains new REST API backed Exchange Online cmdlets which doesn't require WinRM for Client-Server communication. You can now run these cmdlets after turning off WinRM Basic Auth in your client machine thus making it more secure.

Unlike the EXO* prefixed cmdlets, the cmdlets in this module support full functional parity with the RPS (V1) cmdlets.

V3 cmdlets in the downloaded module are resilient to transient failures, handling retries and throttling errors inherently.

However, REST backed EOP and SCC cmdlets are not available yet. To use those, you will need to enable WinRM Basic Auth.

For more information check https://aka.ms/exov3-module
----------------------------------------------------------------------------------------
```

And if I immediately try the `Connect-M365Tenant` cmdlet again, I see this error instead now:
```
Connect-M365Tenant -Credential $creds -Workload ExchangeOnline -Verbose
Error Acquiring Token:
System.ArgumentException: The user is not recognized as a managed user, or a federated user.Azure AD was not able to identify the IdP that needs to process the user U/P: Wrong username ---> Microsoft.Identity.Client.MsalClientException: Unsupported User Type 'Unknown'. Please see https://aka.ms/msal-net-up.
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.<FetchAssertionFromWsTrustAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetTokenForWebApiUsingUsernamePasswordAsync>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetTokenForWebApiUsingUsernamePasswordAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.<GetAccessTokenAsync>d__29.MoveNext()
The user is not recognized as a managed user, or a federated user.Azure AD was not able to identify the IdP that needs
to process the user U/P: Wrong username
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.0.0\netFramework\ExchangeOnlineManagement.psm1:726 char:21
+                     throw $_.Exception.InnerException;
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : The user is not recognized as a managed user, or a federated user.Azure AD was not able
   to identify the IdP that needs to process the user U/P: Wrong username
```

Thank you!

**Comment by desmay** [comment]
@tehmichael Sorry I was out on vacation. I was planning to do some troubleshooting and it appears I lost access to my GCCH tenant. I'm hoping to get access restored by next week to dig further into this issue. Apologies for the delay.

**Comment by tehmichael** [comment]
@desmay no worries!  I appreciate ya taking a look at this case 😄

**Comment by tehmichael** [comment]
@desmay Sounds good!  I'll hang tight then :)

**Comment by desmay** [comment]
@tehmichael Submitted PR should be in next week's release
