### ISSUE TITLE
Issues while exporting TeamsTeam and TeamsUpdateManagementPolicy componemts 

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2660]
#### Details of the scenario you tried and the problem that is occurring

- Ran the command  "Export-M365DSCConfiguration -Components @("TeamsTeam", "TeamsUpdateManagementPolicy") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId"
![image](https://user-images.githubusercontent.com/22946692/207089547-b99c28fe-4dac-479b-b879-e7e198704a8d.png)
- With GA Credentials "TeamsTeam " is working fine but "TeamsUpdateManagementPolicy" fails with error.
![image](https://user-images.githubusercontent.com/22946692/207090800-055f9a66-c0be-4a0b-a5b3-06ed564e3a1d.png)

#### Verbose logs showing the problem
- Error file attached
- error logs show issues with SystemDate and Null-valued expressions
- ----error in file ------
[2022-12-12 09:11:56]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_TeamsTeam\MSFT_TeamsTeam.psm1: line 683
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
TenantId: maheshms365.onmicrosoft.com

[2022-12-12 09:12:03]
{InvalidOperation}
System.Management.Automation.RuntimeException: Method invocation failed because [System.DateTime] does not contain a method named 'Split'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_TeamsUpdateManagementPolicy\MSFT_TeamsUpdateManagementPolicy.psm1: line 93
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_TeamsUpdateManagementPolicy\MSFT_TeamsUpdateManagementPolicy.psm1: line 382
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
TenantId: maheshms365.onmicrosoft.com

#### Suggested solution to the issue
May be issue is same as #2654. Where is script is not able to handle Null values and Systemdate
#### The operating system the target node is running
OsName : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture : 64-bit
WindowsVersion : 2009
WindowsBuildLabEx : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage : en-US
OsMuiLanguages : {en-US, en-GB}

**Comment by maheshdalavi** [comment]
[38328-M365DSC-ErrorLog.log](https://github.com/microsoft/Microsoft365DSC/files/10209741/38328-M365DSC-ErrorLog.log)

**Comment by NikCharlebois** [comment]
This has been fixed and will be released with 1.22.1214.1 on Wednesday. See #2639
