### ISSUE TITLE
ResourceName: SPO* -> export configuration for all SPO resources fail using a SPN with error (403) Forbidden.

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2763]
#### Details of the scenario you tried and the problem that is occurring
I use as Service Principal with the following API permissions set with Admin Consent
![image](https://user-images.githubusercontent.com/84451910/211546719-da18e925-2b58-492a-8f33-0d62b1323441.png)

According to the documentation the use of Service Principal for workload SPO is supported, see screenshot
![image](https://user-images.githubusercontent.com/84451910/211547393-6b4259b6-74ff-4448-8c68-4d4272ddaf3a.png)

When running e.g. the command `Export-M365DSCConfiguration -Components @("SPOAccessControlSettings") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId` The result is....
![image](https://user-images.githubusercontent.com/84451910/211547764-9599ba31-4e32-47ab-a70e-8230ff41c57f.png)

The errorfile shows the following error;
```text
[2023-01-10 12:57:10]
{WriteError}
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.PowerShell.Commands.Admin.GetTenant.ExecuteCmdlet()
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.104.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 116
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.104.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 492
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.104.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.104.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com
```

#### Verbose logs showing the problem
Verbose output available in the attached file
[PowerShell_transcript.txt](https://github.com/microsoft/Microsoft365DSC/files/10382639/PowerShell_transcript.txt)

#### Suggested solution to the issue

Would love to know why the access forbiden message is thrown

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.25272.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25272.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```powershell
ModuleBase                                                            Version
----------                                                            -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.104.1 1.23.104.1
```

Also module dependencies wereupdated before the issue occured (including removing outdated modules)

**Comment by MarcelHeek** [comment]
Additional info : 

Connect-PNPOnline using the SPN succeeds without errors. However executing Get-PnPTenant failed --> The remote server returned an error: (403) Forbidden.

**Comment by bjoernf73** [comment]
@MarcelHeek I believe it lacks from the documentation that you must add the SPN to the SharePoint Online Admin group....it simply doesn't seem to work without that.

**Comment by NikCharlebois** [comment]
You shouldn't have to add the SPN to the SPo Admin Group. Simply make sure that the SPN is granted the Sites.FullControl permissions from the SharePoint provider (not Microsoft Graph).

**Comment by MarcelHeek** [comment]
I added a certificate to the Service Principal and using the Thumbprint based authentication works just fine, with the API permissions set as show in the screenshot in the issue. So from API permissions PoV the right permissions are set to the Service Principal. No need to add the SPN to a role or admin group. 

However using a secret is just way easier especially in the construct of building a GitHub pipeline. So the documentation suggests a secret should work, but maybe the documentation is incorrect and the "best" method is using certificate based (thumbprint) as that works okay. The option to specify `-CertificatePath <path> -CertificatePassword <password>` in my case also failed as I get a Credential prompt with the password of the certificate already filled in, cancelling the credential prompt results in collection errors.

So for me I have refactored my GitHub workflow to using a thumbprint now, but either the other methods need fixing or should be properly documented.

**Comment by NikCharlebois** [comment]
Adding @desmay to the thread.

**Comment by NikCharlebois** [comment]
Client Secret auth in SharePoint uses the legacy ACS model. You will need to follow the instructions on this page:
https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

Starting at the second step (skip the part where you need to create a new app) and use your own App ID that you created.
![image](https://user-images.githubusercontent.com/2547149/218763607-6687009d-7902-4678-b98e-2292d5c71263.png)
![image](https://user-images.githubusercontent.com/2547149/218763686-c7be5a10-68dd-48bd-855a-0e3da73a79bf.png)

We will update the official documentation on the web site to reflect this.
