### ISSUE TITLE
PlannerPlan : TerminatingError(Get-M365DSCExportContentForResource): "You cannot call a method on a null-valued expression."

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2795]
#### Details of the scenario you tried and the problem that is occurring

I am trying to export the Planner configuration for a tenant using Certificate Thumbprint authentication and I receive occasional error as can be seen below (redacted the names of the planner items). the fact that I get the PS prompt with error is because I used start-transcript before running the command.

```text
Exporting Microsoft 365 configuration for Components: PlannerPlan, PlannerTask

Authentication methods specified:
- Service Principal with Certificate Thumbprint

Connecting to {MicrosoftGraph}...
✅
[1/2] Extracting [
PlannerPlan
] using {
CertificateThumbprint
}...

    [1/25346] <redacted> - {GUID}
    [2/25346] <redacted> - {GUID}
        [1/1] <redacted> 
PS>TerminatingError(Get-M365DSCExportContentForResource): "You cannot call a method on a null-valued expression."
❌
Error Log created at {file://D:/a/m365dsc-reporter/m365dsc-reporter/1456-M365DSC-ErrorLog.log}
    [2/25346] <redacted> - {GUID}
    [3/25346] <redacted>  - {GUID}
        [1/1] <redacted> 
PS>TerminatingError(Get-M365DSCExportContentForResource): "You cannot call a method on a null-valued expression."
❌
Error Log created at {file://D:/a/m365dsc-reporter/m365dsc-reporter/1456-M365DSC-ErrorLog.log}
    [3/25346] <redacted> - {GUID}
    [4/25346] <redacted> - {0GUID}
    [5/25346] <redacted> - {GUID}
    [6/25346] <redacted> - {GUID}
    [7/25346] <redacted>  - {GUID}
    [8/25346] <redacted>  - {GUID}
    [9/25346] <redacted>  - {GUID}
    [10/25346] <redacted>  - {GUID}
        [1/1] <redacted>
PS>TerminatingError(Get-M365DSCExportContentForResource): "You cannot call a method on a null-valued expression."
❌
Error Log created at {file://D:/a/m365dsc-reporter/m365dsc-reporter/1456-M365DSC-ErrorLog.log}
    [10/25346] <redacted>  - {GUID}
    [11/25346] <redacted>  - {GUID}
```

#### Verbose logs showing the problem

The messages written to the errorlog.log file are like the ones below

```text
[2023/01/17 08:35:07]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 2898
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_PlannerPlan\MSFT_PlannerPlan.psm1: line 402
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, D:\a\m365dsc-reporter\m365dsc-reporter\_scripts\Collect_M365DSC_Report_v0.2.ps1: line 96
at <ScriptBlock>, D:\a\_temp\846036d6-48b4-4a46-acd1-6bc6044a498a.ps1: line 2
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com

[2023/01/17 08:35:08]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 2898
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_PlannerPlan\MSFT_PlannerPlan.psm1: line 402
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, D:\a\m365dsc-reporter\m365dsc-reporter\_scripts\Collect_M365DSC_Report_v0.2.ps1: line 96
at <ScriptBlock>, D:\a\_temp\846036d6-48b4-4a46-acd1-6bc6044a498a.ps1: line 2
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com
```

#### Suggested solution to the issue

Correct the collection script

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
Export-M365DSCConfiguration -Components @("PlannerPlan", "PlannerTask") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbPrint -TenantId $TenantId -Path $ReportDir -GenerateInfo $true -Mode $Mode 
```

#### The operating system the target node is running
```text
OsName               : Microsoft Windows Server 2022 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-[15](https://github.com/VolkerWessels/m365dsc-reporter/actions/runs/3937385376/jobs/6734843431#step:6:16)00
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

Version Microsoft DSC installed: 1.23.111.1

**Comment by andikrueger** [comment]
Is this also happening if you do not run a transcript of the export?

**Comment by MarcelHeek** [comment]
I see no differences running with or without transcript. Only the error is not shown, see below

```text
Exporting Microsoft 365 configuration for Components: PlannerPlan, PlannerTask

Authentication methods specified:
- Service Principal with Certificate Thumbprint

Connecting to {MicrosoftGraph}...✅
[1/2] Extracting [PlannerPlan] using {CertificateThumbprint}...
    [1/25340] <replaced> - {GUID}
    [2/25340] 203548 - <replaced> - {GUID}
        [1/1] via-tender-203548-t
❌
Error Log created at {file://C:/temp/M365DSC/issues/2795/39568-M365DSC-ErrorLog.log}
    [2/25340] <replaced> - {GUID}
    [3/25340] <replaced> - {GUID}
        [1/1] <replaced>
❌
Error Log created at {file://C:/temp/M365DSC/issues/2795/39568-M365DSC-ErrorLog.log}
    [3/25340] <replaced> - {GUID}
    [4/25340] <replaced> - {GUID}
```

and the content is the error file is also the same.
```text
[2023-01-18 12:52:43]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 2898
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_PlannerPlan\MSFT_PlannerPlan.psm1: line 402
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com
```

**Comment by NikCharlebois** [comment]
Can you confirm that your app registration has the following app permissions granted?
Tasks.ReadWrite.All or Tasks.Read.All

**Comment by NikCharlebois** [comment]
Also, can you confirm:

 - What PowerShell version you are using
 - The path where all the modules are installed (M365DSC, Microsoft.Graph.*, etc.)
 - That you have run the Update-M365DSCModule cmdlet

**Comment by jeffreykarlan** [comment]
@NikCharlebois 

Thank you:

- 
![image](https://user-images.githubusercontent.com/13066498/219729553-f74c4de4-d6d8-4e73-9751-6d7db2ed1448.png)

-
![image](https://user-images.githubusercontent.com/13066498/219731217-c77dee9b-6251-400b-b7de-9253f60384d7.png)

-
![image](https://user-images.githubusercontent.com/13066498/219734029-cdb4bfaa-525b-4bc7-bf1d-b6be7fc2acab.png)

- I've not update the module since v. 1.23.201.1

Thank you

**Comment by NikCharlebois** [comment]
@jeffreykarlan looks like you may be having a different error. The screenshot you had originally posted talks about Teams. For Teams, you still need to grant your App Registration Teams Administrator RBAC permission.

Going back to @MarcelHeek original issue, we have made several improvements to Planner over the past few weeks. Can you please update to the latest version and confirm if you are still seeing the issue with it? We are not able to replicate on our test tenants.

**Comment by NikCharlebois** [comment]
Closing due to inactivity
