### ISSUE TITLE
[SharePoint] Can't connect with SharePoint after a tenant rename

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#2803]
#### Details of the scenario you tried and the problem that is occurring
After a [tenant rename](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name) Microsoft365DSC is no longer able to connect to SPO/OD. You are constantly getting 403 Forbidden errors.

When investigating, it turns out that the MSCloudLoginAssistant keeps generating the old Admin portal URL. Get-PnPContext shows the old url. The code (see below) retrieves the initial tenant.onmicrosoft.com and then replaces ".onmicrosoft.com" with "-admin.sharepoint.com". This results in the old Admin portal url instead of the new one.

Current code:

https://github.com/microsoft/MSCloudLoginAssistant/blob/090357852e5a68ab57031ecfe5b28ae32c93e9bc/Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1#L325

https://github.com/microsoft/MSCloudLoginAssistant/blob/090357852e5a68ab57031ecfe5b28ae32c93e9bc/Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1#L418-L431

#### Verbose logs showing the problem
```
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.PowerShell.Commands.Admin.GetTenant.ExecuteCmdlet()
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 116
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 492
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
```
#### Suggested solution to the issue
We need a way to generate the correct URL after a tenant rename.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by bjoernf73** [comment]
@ykuijs it would be nice if you could try my suggestion above? This may resolve this issue. 

@NikCharlebois This is a duplicate of my issue https://github.com/microsoft/MSCloudLoginAssistant/issues/137 in the MSCloudLoginAssistant repository, resolved by PR  https://github.com/microsoft/MSCloudLoginAssistant/pull/139

**Comment by ykuijs** [comment]
Hi @bjoernf73, thanks for sharing this. Hadn't seen that PR yet.

In the meantime I also found a solution. That solution isn't relying on the redirect, but uses the Graph API to request the SharePoint URL:

```PowerShell
Connect-MgGraph -Scopes Sites.Read.All
$result = Invoke-MgGraphRequest -Uri /v1.0/sites/root
$result.webUrl
$result.webUrl -replace "\.sharepoint\.com","-admin.sharepoint.com"
```

Let me check what solution we would like to use here.

**Comment by ykuijs** [comment]
To make sure this code also works for GCCH and DOD, we need to update the replace statement a little:
```PowerShell
Connect-MgGraph -Scopes Sites.Read.All
$result = Invoke-MgGraphRequest -Uri /v1.0/sites/root
$result.webUrl -replace "^https:\/\/(\w*)\.",'https://$1-admin.'
```

**Comment by ykuijs** [comment]
Just created a PR to fix this issue: https://github.com/microsoft/MSCloudLoginAssistant/pull/144

**Comment by ykuijs** [comment]
PR in MSCloudLoginAssistant is merged and a new version is released. This new version will be included in the tomorrows release. Closing issue now.
