### ISSUE TITLE
SPO+OD caching certificate creds?

### ISSUE THREAD

**Issue by martincaddick** [microsoft/Microsoft365DSC#3067]
Something funky going on with SPO+OD and certthumbprint+appid+tenantid auth

Issue is in module version 1.23.322.1 but I believe it has been in earlier.

The script below:
1. Connects to the source tenant and exports SPO, OD and O365 settings
2. Loops thru the .ps1 files and copies them to .m365 files
3. Use the .m365 files and checks the target tenant using the .m365 file as the blueprint

Works correctly for O365.ps1 in all cases, fails with 401 error shown at the end of this post for all OD and SPO components.

If I comment out the Export parts and re-run the script _in the same powershell session_ it also fails in the same manner.

However, if I then take that code (so I'm not doing the export and therefore authing to the source tenant) and run this in a new powershell session then the script works perfectly

It's almost as though it is caching the cert details from the source connection and trying to use them for the target connection.

```
==== Script start ====
# Setting application information for Application + Certificate authentication for Source Tenant
$ApplicationId = 'xxxx'
$CertificateThumbprint = 'xxxx'
$TenantId = 'sourcetenant.onmicrosoft.com'
$fileLocation = "C:\Source\"
$fullStartTime = Get-Date

# Setting application information for Application + Certificate authentication for Target Tenant
$TargetApplicationId = 'yyyyyy'
$TargetCertificateThumbprint = 'yyyyy'
$TargetTenantId = 'targettenant.onmicrosoft.com'

# Export SPO info
$startTime = Get-Date
$comp = @("SPOAccessControlSettings", "SPOBrowserIdleSignout", "SPOHomeSite", "SPOOrgAssetsLibrary", `
"SPOSharingSettings", "SPOSiteDesignRights", "SPOSiteScript", "SPOStorageEntity", "SPOTenantCdnEnabled", `
"SPOTenantCdnPolicy", "SPOTheme")
Export-M365DSCConfiguration -Components $comp `
-ApplicationId $ApplicationId `
-CertificateThumbprint $CertificateThumbprint `
-TenantId $TenantId `
-Path $fileLocation `
-FileName "SPO.ps1"
$endTime = Get-Date
Write-Host "Processing time for SPO was"($endTime-$startTime)

# Export OD info
$startTime = Get-Date
$comp = @("ODSettings")
Export-M365DSCConfiguration -Components $comp `
-ApplicationId $ApplicationId `
-CertificateThumbprint $CertificateThumbprint `
-TenantId $TenantId `
-Path $fileLocation `
-FileName "OD.ps1"
$endTime = Get-Date
Write-Host "Processing time for OneDrive was"($endTime-$startTime)

# Export O365 info
$startTime = Get-Date
$comp = @("O365AdminAuditLogConfig", "O365OrgCustomizationSetting", "O365OrgSettings")
Export-M365DSCConfiguration -Components $comp `
-ApplicationId $ApplicationId `
-CertificateThumbprint $CertificateThumbprint `
-TenantId $TenantId `
-Path $fileLocation `
-FileName "O365.ps1"
$endTime = Get-Date
Write-Host "Processing time for O365 was"($endTime-$startTime)

# Blueprint Reports configuration. 
# Create html files with the differences between the Source and Target tenants. The Source is considered to be the Blueprint.
if(!(Test-Path -Path ($fileLocation + "\BlueprintReports"))){mkdir ($fileLocation + "\BlueprintReports")}
$files = Get-ChildItem -Path $fileLocation -Filter *.ps1

# Create blueprint delta reports
foreach ($file in $files)
{
    $startTime = Get-Date
    Write-Host "Generate blueprint assessment for $($file)"
    # Creating the blueprint from the export 
    $blueprint = Copy-Item -Path $file.fullname -Destination ($fileLocation + "\" + $file.name.split(".")[0] + ".m365") -PassThru
    $outputpath = (($fileLocation + "\BlueprintReports\") + $file.name.split(".")[0] + ".html")
    Assert-M365DSCBlueprint -BluePrintUrl $blueprint -OutputReportPath $outputpath -ApplicationId $TargetApplicationId `
    -TenantId $TargetTenantId -CertificateThumbprint $TargetCertificateThumbprint `
    -Type HTML -ExcludedProperties Id, ExcludedUsers
    $endTime = Get-Date
    Write-Host "Processing time for $($file) is $($endTime - $startTime)"
}

$fullEndTime = Get-Date
Write-Host "Total processing time is"($fullEndTime-$fullStartTime)
===== Script End=====
```

```
========================
Sample Error thrown
========================

[2023/03/23 11:50:33]
{WriteError}
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.PowerShell.Commands.Admin.GetTenantCdnPolicies.ExecuteCmdlet()
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_SPOTenantCdnPolicy\MSFT_SPOTenantCdnPolicy.psm1: line 75
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_SPOTenantCdnPolicy\MSFT_SPOTenantCdnPolicy.psm1: line 400
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\modules\M365DSCUtil.psm1: line 1207
at Assert-M365DSCBlueprint, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\modules\M365DSCUtil.psm1: line 2542
at <ScriptBlock>, <No file>: line 65
TenantId: targettenant.onmicrosoft.com
```

**Comment by andikrueger** [comment]
Please review this comment on how to reset the connection in this case: https://github.com/microsoft/Microsoft365DSC/issues/2964#issuecomment-1457748867

**Comment by martincaddick** [comment]
Thanks @andikrueger, I've just tried inserting this line
$Global:MSCloudLoginConnectionProfile.PnP.Connected = $false
after the export but before the assert. No difference. Maybe I misunderstood.

**Comment by andikrueger** [comment]
This is what I would have done as well. 

What PS Version are you using?

**Comment by martincaddick** [comment]
PSVersion                      5.1.17763.3770

**Comment by JohnT-Aus** [comment]
Hi All,

I found the same situation was happening when doing something very similar for Teams only.  IE, I was exporting for multiple Tenants from the same script instance and it would never use anything but the first set of Credentials and thus seemed to be cached and unless I changed PowerShell Sessions, these Credentials remained.

I tried the above but this didn't happen do I went looking in the M365DSCUtil.psm1 and found where a check is made if an existing MSGraph connection has been established and as such, I added the following to my script and NOW, I'm able to get the details for the various Tenants.  Phew!

    try
    {
        Disconnect-MicrosoftTeams -ErrorAction Stop | Out-Null
        $Global:MSCloudLoginConnectionProfile.Teams.Connected = $false
    }
    catch
    {
        Write-Verbose -Message "No existing connections to Microsoft Teams"
    }
    
It might be worth trying that (or the equivalent) @martincaddick as I think the "Disconnect" is freeing those credentials as the - "$Global:MSCloudLoginConnectionProfile.Teams.Connected = $false" - wasn't having the desired effect.
    
Is this the needed approach perhaps for those of us calling specific components?
    
I hope this is helpful.  Thanks.

**Comment by NikCharlebois** [comment]
I would recommend clearing the entire Global Variable if you are using a single runspace to interact with multiple tenants. E.g.,

```
$Global:MSCloudLoginConnectionProfile = $null
```

We understand this seems like a complicated solution, but using this Global variable is the best way to handle token caching for all the various workloads we support.

**Comment by martincaddick** [comment]
@NikCharlebois 
That works perfectly, thanks
