### ISSUE TITLE
Running Export-M365DSCConfiguration results in no output with 'Cannot bind argument to parameter 'ReferenceObject' because it is null'

### ISSUE THREAD

**Issue by jcizek84** [microsoft/Microsoft365DSC#3261]
ISSUE TITLE:
    M365DSC no output / failing. 

    ISSUE DESCRIPTION :
    When running the command as generated from the WebUI it fails -  I´ve tried in multiple tenants but there is no output in any of them. The suggested path with partial.ps1 never exists. When I try to run the command the output is: 
    
    Authentication methods specified:
    - Service Principal with Certificate Thumbprint

    [WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
    TeamsUserCallingSettings
    Connecting to {ExchangeOnline}...❌
    Cannot bind argument to parameter 'ReferenceObject' because it is null.
    Partial Export file was saved at: C:\Users\CIZEKJ~1\AppData\Local\Temp\5e778245-b8c5-4b94-be70-5ef9e9659411.partial.ps1  

-->
#### Details of the scenario you tried and the problem that is occurring

- I created the Azure App
- ran 

#### Verbose logs showing the problem
If I run it using -verbose: 

Error Log created at {file://C:/Users/CizekJan(KPCSCZ)/OneDrive - KPCS CZ/_DEVOPS/Delivery/32504-M365DSC-ErrorLog.log}
Partial Export file was saved at: C:\Users\CIZEKJ~1\AppData\Local\Temp\d2c8505b-f55b-4a82-8da4-a9eb0645b310.partial.ps1
The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCUtil.psm1:1352 char:13
+             throw $ErrorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The following d...edDependencies.:String) [], RuntimeException
    + FullyQualifiedErrorId : The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.

The Error log shows this: 

[2023.05.02 04:14:11]
{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "SourceExists" with "1" argument(s): "The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security." ---> System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at CallSite.Target(Closure , CallSite , Type , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Could not write to event log Source {M365DSCUtil} EntryType {Error} Message {The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.}"
at Add-M365DSCEvent, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCLogEngine.psm1: line 194
at Confirm-M365DSCDependencies, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCUtil.psm1: line 1350
at New-M365DSCConnection, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCUtil.psm1: line 1661
at Get-M365DSCTenantDomain, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCUtil.psm1: line 1478
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCReverse.psm1: line 252
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.426.3\modules\M365DSCUtil.psm1: line 1280
at <ScriptBlock>, <No file>: line 17

I did run the update and Uninstall multiple times, I used -Force for the Update etc. Nothing helps. 
Tried in Terminal / VS Code / ISE
Ran in PS 5.1
Ran in 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
The command that was ran: 

$Params = @{
    TenantId = $TenantId
    ApplicationId = $ApplicationId
    CertificateThumbprint = $CertificateThumbprint
    Components = @("AADTenantDetails")
    FileName = "C:\Temp\Configuration.ps1"
    Verbose = $true
}
Export-M365DSCConfiguration @params

#### My config

OsName  : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture  : 64-bit
WindowsVersion  : 2009
WindowsBuildLabEx : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage   : en-GB
OsMuiLanguages : {en-GB, cs-CZ, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

Manifest   1.23.426.3       Microsoft365DSC

**Comment by jcizek84** [comment]
> Could you share your version of MSCloudLoginAssistant? There was an issue last week, that sounds like the one you have right now.
> 
> Get-Module MSCloudLoginAssistant -ListAvailable

Here it is: 

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Script     1.0.108    MSCloudLoginAssistant               {Test-MSCloudLogin, Connect-M365Tenant, Invoke-MSCloudLoginMicrosoftGraphAPI, Get-PowerPlatformTokenInfo...}

**Comment by NikCharlebois** [comment]
I would recommend updating to the latest version to solve your issue. Simply run:

```powershell
Update-M365DSCModule
```

**Comment by jcizek84** [comment]
I ran the update multiple times - no change there. I'll post results, but it's freshly installed in VM  ran update module, update of dependencies and remove of dependencies.

Zasláno z Outlooku pro Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NikCharlebois** [comment]
Closing due to inactivity
