### ISSUE TITLE
EXOAvailabilityConfig component script - unhandled error when OrgWideAccount is empty

### ISSUE THREAD

**Issue by PierreColyn** [microsoft/Microsoft365DSC#3402]
When I try to run the EXOAvailabilityConfig component with a certificate thumbprint I get the following error in the error log:

{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Users\#Username#\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.614.1\DSCResources\MSFT_EXOAvailabilityConfig\MSFT_EXOAvailabilityConfig.psm1: line 351
at Start-M365DSCConfigurationExtract, C:\Users\#Username#\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.614.1\modules\M365DSCReverse.psm1: line 619
at Export-M365DSCConfiguration, C:\Users\#Username#\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.614.1\modules\M365DSCUtil.psm1: line 1308
at <ScriptBlock>, <No file>: line 1
TenantId: #Tenant ID#

This is due to the OrgWideAccount not been set in the selected environment.

Please add error handling to check if the OrgWideAccount is empty (line 352 of script).

**Comment by andikrueger** [comment]
Thanks for reporting! We'll look into it.
