### ISSUE TITLE
AADCrossTenantAccessPolicyConfigurationPartner : Issue adding additional property

### ISSUE THREAD

**Issue by tayhall** [microsoft/Microsoft365DSC#3489]
### Description of the issue

MSFT_AADCrossTenantAccessPolicyConfigurationPartner: Adding AutomaticUserConsentSettings
Ive uploaded my fork with some additional changes to the AADCrossTenantPartner module but I cannot see what I have done wrong.

Just looking for some pointers as a new contributor

Thanks
:) 

### Microsoft 365 DSC Version

V1.23.719.1

### Workload

Azure Active Directory

### The DSC configuration

Export-M365DSCConfiguration -Components @("AADCrossTenantAccessPolicyConfigurationPartner")  -GenerateInfo:$true -ApplicationId $ApplicationID -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

### Verbose logs showing the problem

System.Management.Automation.RuntimeException: Cannot convert the "Microsoft.Graph.Beta.PowerShell.Models.MicrosoftGraphInboundOutboundPolicyConfiguration" value of type "Microsoft.Graph.Beta.PowerShell.Models.MicrosoftGraphInboundOutboundPolicyConfiguration" to type "Microsoft.Management.Infrastructure.CimInstance". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "Microsoft.Graph.Beta.PowerShell.Models.MicrosoftGraphInboundOutboundPolicyConfiguration" value of type "Microsoft.Graph.Beta.PowerShell.Models.MicrosoftGraphInboundOutboundPolicyConfiguration" to type "Microsoft.Management.Infrastructure.CimInstance".
   at System.Management.Automation.LanguagePrimitives.ConvertCheckingForCustomConverter.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.719.1\DSCResources\MSFT_AADCrossTenantAccessPolicyConfigurationPartner\MSFT_AADCrossTenantAccessPolicyConfigurationPartner.psm1: line 113
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.719.1\DSCResources\MSFT_AADCrossTenantAccessPolicyConfigurationPartner\MSFT_AADCrossTenantAccessPolicyConfigurationPartner.psm1: line 480
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.719.1\modules\M365DSCReverse.psm1: line 620
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.719.1\modules\M365DSCUtil.psm1: line 1310
at <ScriptBlock>, <No file>: line 78

**Comment by andikrueger** [comment]
Could you share your branch somewhere to get a better understanding of the resource?

**Comment by tayhall** [comment]
Hi

Is my fork visible?

I've checked my commits in

https://github.com/tayhall/Microsoft365DSC

The changes are just in the cross tenant partner module

Thanks

**Comment by andikrueger** [comment]
Yes it is. It looks like you added a new class to the schema.mof file but did not integrate this change in the class description of the resource.

**Comment by tayhall** [comment]
Ok I'll have a look thanks.

Should the class description be in the module or is there another file that
references all of these?

**Comment by andikrueger** [comment]
It should be in this file here:

https://github.com/microsoft/Microsoft365DSC/compare/Dev...tayhall:Microsoft365DSC:Dev#diff-d721202e026eefe713176445b510985bc7541617e9b8d4d07e4a513af6b376ba

You can implement similar to Line 42 for B2BCollaborationOutbound.

**Comment by tayhall** [comment]
Appreciate the help and have updated but its still not happy. I cannot see anywhere I'm missing in this file. I've also updated the logs above with the latest error.

**Comment by ykuijs** [comment]
Fixed via PR #3502
