### ISSUE TITLE
Microsoft.Graph.PowerShell.AuthenticationException: Authentication needed. Please call Connect-MgGraph.

### ISSUE THREAD

**Issue by kami-delaroz** [microsoft/Microsoft365DSC#3532]
I'm trying to run Export-M365DSCConfiguration on ubuntu. I'm getting the error:
`Microsoft.Graph.PowerShell.AuthenticationException: Authentication needed. Please call Connect-MgGraph.
   at Microsoft.Graph.PowerShell.Authentication.Core.Utilities.AuthenticationHelpers.GetAuthenticationProviderAsync(IAuthContext authContext)
   at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient()
   at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
   at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()^M
"Error during Export:"^M
at Get-MgGroup<Process>, /root/.local/share/powershell/Modules/Microsoft.Graph.Groups/2.1.0/exports/ProxyCmdletDefinitions.ps1: line 42527
at Export-TargetResource, /root/.local/share/powershell/Modules/Microsoft365DSC/1.23.719.1/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1: line 1041
at Start-M365DSCConfigurationExtract, /root/.local/share/powershell/Modules/Microsoft365DSC/1.23.719.1/Modules/M365DSCReverse.psm1: line 620
at Export-M365DSCConfiguration, /root/.local/share/powershell/Modules/Microsoft365DSC/1.23.719.1/Modules/M365DSCUtil.psm1: line 1313
at <ScriptBlock>, <No file>: line 1^M
batel@6374cm.onmicrosoft.com^M
TenantId: 6374cm.onmicrosoft.com^M`

I tried to run `Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"`
in the pwsh session, and got the `Welcome To Microsoft Graph!` message,
but still got the same error when running the export.

I tried to add the connect call in the DSC code, just before the Get-MgGroup, but I got
`Connect-MgGraph: Authentication timed out after 120 seconds due to inactivity. Please try again.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code A5SC696EC to authenticate.`

I'm not sure why the url auth request was not printed before the auth time out error.

currently trying to generate a certificate in my ubuntu machine and use it in a certificate based connect command:
Connect-MgGraph -ClientID ‘xxx’ -TenantId ‘yyy.onmicrosoft.com’ -CertificateThumbprint ‘zzz’
but having issues in this direction as well :/

**Comment by kami-delaroz** [comment]
I got the exact same error in Windows:
`[2023/07/27 01:06:05]
{NotSpecified}
Microsoft.Graph.PowerShell.AuthenticationException: Authentication needed. Please call Connect-MgGraph.
   at Microsoft.Graph.PowerShell.Authentication.Core.Utilities.AuthenticationHelpers.<GetAuthenticationProviderAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient()
   at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
   at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.<ProcessRecordAsync>d__84.MoveNext()
"Error during Export:"
at Get-MgGroup<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\2.1.0\exports\ProxyCmdletDefinitions.ps1: line 42527
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_AADGroup\MSFT_AADGroup.psm1: line 1041
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\modules\M365DSCReverse.psm1: line 620
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\modules\M365DSCUtil.psm1: line 1310
at <ScriptBlock>, <No file>: line 2
batel@6374cm.onmicrosoft.com
TenantId: 6374cm.onmicrosoft.com`
But a second export run finished successfully
