### ISSUE TITLE
Apostrophe's in DisplayName of a Teams Channel Tab causes a null reference

### ISSUE THREAD

**Issue by 808d1** [microsoft/Microsoft365DSC#3535]
### Description of the issue

Tabs in a channel allow apostrophes in the DisplayName.  

When exporting TeamsChannelTab, the call to Get-MgBetaTeamChannelTab is erroring silently, resulting in a null return when a single quote (apostrophe) is in the DisplayName of the Channel Tab.

This can be replicated by simply adding a Wiki to an existing Teams channel's General tab and labeling it as "Joe's Wiki".

I can work around this issue by adding the following line of code above line 155 in MSFT_TeamsChannelTab.psm1, which escapes the single quote before the call to Get-MgBetaTeamChannelTab:
`if($DisplayName.IndexOf("'") -gt 0) { $DisplayName = $DisplayName -replace "'", "''"}`

### Microsoft 365 DSC Version

1.23.809.1

### Which workloads are affected

Teams

### Verbose logs showing the problem

{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\modules\M365DSCUtil.psm1: line 3296
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_TeamsChannelTab\MSFT_TeamsChannelTab.psm1: line 581
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\modules\M365DSCReverse.psm1: line 620
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\modules\M365DSCUtil.psm1: line 1310

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.19041.3031
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.19041.3031
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by FabienTschanz** [comment]
This should be fixed by now.
