### ISSUE TITLE
Error in Exporting AADAdministrativeUnit 

### ISSUE THREAD

**Issue by toby17780** [microsoft/Microsoft365DSC#3618]
### Description of the issue

Exporting AADAdministrativeUnit ends with following Error:

`[2023.08.29 12:06:44]
{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CallSite.Target(Closure , CallSite , String , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Convert-DSCStringParamToVariable, C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.16\ReverseDSC.Core.psm1: line 766
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.823.1\DSCResources\MSFT_AADAdministrativeUnit\MSFT_AADAdministrativeUnit.psm1: line 1078
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.823.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.823.1\modules\M365DSCUtil.psm1: line 1310
at <ScriptBlock>, C:\Tools\Scripts\M365DSCBackup.ps1: line 25
at <ScriptBlock>, <No file>: line 1`

### Microsoft 365 DSC Version

1.23.823.1

### Which workloads are affected

Azure Active Directory

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE, es-ES, fr-FR...}

Key   : PSVersion
Value : 5.1.17763.4720
Name  : PSVersion
```

**Comment by toby17780** [comment]
Sind last Update it works without problems for me. Thank you very much...
