### ISSUE TITLE
SPO System.Net.WebException: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoft/Microsoft365DSC#3807]
Hello,

I have this error since a while when I try to extract some configurations of SPO using certificate. Some configuration are working fine, but some not. I have installed the latest version of DSC.

Error in the file 10508-M365DSC-ErrorLog.log
{WriteError}
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.PowerShell.Commands.Admin.GetTenant.ExecuteCmdlet()
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1011.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 116
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1011.1\DSCResources\MSFT_SPOAccessControlSettings\MSFT_SPOAccessControlSettings.psm1: line 492
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1011.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1011.1\modules\M365DSCUtil.psm1: line 1292
at <ScriptBlock>, C:\IO Collaboration\DSC\DSC_exportConfig.ps1: line 211
at <ScriptBlock>, <No file>: line 1
TenantId: <tenant>.onmicrosoft.com

Please find the configuration with this error:
Authentication methods specified:
- Service Principal with Certificate Thumbprint

Connecting to {PnP}...✅
[1/17] Extracting [SPOAccessControlSettings] using {CertificateThumbprint}... Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
✅
[2/17] Extracting [SPOApp] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[3/17] Extracting [SPOBrowserIdleSignout] using {CertificateThumbprint}... Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
❌
[4/17] Extracting [SPOHomeSite] using {CertificateThumbprint}... Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
✅
[5/17] Extracting [SPOHubSite] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[6/17] Extracting [SPOOrgAssetsLibrary] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[7/17] Extracting [SPOSearchManagedProperty] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[8/17] Extracting [SPOSearchResultSource] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[9/17] Extracting [SPOSharingSettings] using {CertificateThumbprint}... Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
✅
[10/17] Extracting [SPOSiteDesign] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[11/17] Extracting [SPOSiteDesignRights] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[12/17] Extracting [SPOSiteScript] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
[13/17] Extracting [SPOStorageEntity] using {CertificateThumbprint}...✅
[14/17] Extracting [SPOTenantCdnEnabled] using {CertificateThumbprint}...
    |---[1/2] Public Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
❌
    |---[2/2] Private Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
❌
[15/17] Extracting [SPOTenantCdnPolicy] using {CertificateThumbprint}...
    |---[1/2] Public Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
❌
    |---[2/2] Private Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
❌
[16/17] Extracting [SPOTenantSettings] using {CertificateThumbprint}... Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
✅
[17/17] Extracting [SPOTheme] using {CertificateThumbprint}...❌
 Error Log created at {file://C:/IO Collaboration/10508-M365DSC-ErrorLog.log}
⌛ Export took {21 seconds}

**Comment by OlivierWaterloos** [comment]
I have checked the permission of the App registration and the permission seems correct:
![image](https://github.com/microsoft/Microsoft365DSC/assets/55983772/9fc949d0-219e-4e09-b70f-7ea249a2c709)

**Comment by andikrueger** [comment]
Is you application within the global reader or global admin role?

**Comment by OlivierWaterloos** [comment]
Thanks for the support.
The app has Global reader and of course Global Admin is not an option. ;-)

**Comment by NikCharlebois** [comment]
The App requires Site.FullControl.All from the SharePoint Provider, not the Microsoft Graph.
![image](https://github.com/microsoft/Microsoft365DSC/assets/2547149/32383bc3-aae6-41f8-b493-213c2d3ebd1e)

**Comment by NikCharlebois** [comment]
![image](https://github.com/microsoft/Microsoft365DSC/assets/2547149/fabee993-7492-4c00-810f-94b7df6d23b8)

**Comment by OlivierWaterloos** [comment]
Thanks Nik. I have add those permissions.
I have this:
    Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName   -Workloads @("$WorkLoad") -Applicati
    onId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
    Exporting Microsoft 365 configuration for Workloads: SPO
    Finding all resources for workload {SPO} and Mode {Default}
    
    Authentication methods specified:
    - Service Principal with Certificate Thumbprint
    
    Partial Export file was saved at: C:\Users\<Myusers>\AppData\Local\Temp\32335634-2eda-4f27-800b-58fe843b860a.partial.ps1
Nothing, No ps1 file generated. I have tried with the component parameters, same issue.

**Comment by OlivierWaterloos** [comment]
In the meanwhile I have install the latest version of DSC.

**Comment by andikrueger** [comment]
The global reader role is not supported by OneDrive nor SharePoint as soon as you try to connect using PowerShell:

https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#global-reader

**Comment by OlivierWaterloos** [comment]
So do I need to remove the role Global reader Role of my user?

**Comment by andikrueger** [comment]
You would need to have a SharePoint Admin role for your application or user.

**Comment by OlivierWaterloos** [comment]
Hello,
Indeed it's working better with the role for this app reg.
Thanks

**Comment by ResearchAndDevelopment00** [comment]
I am facing the exact same error. @OlivierWaterloos can you kindly mention the exact steps that helped you get the solution? Thank you.

`[2024-05-01 03:00:41]
{WriteError}
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<GetFormDigestInfoPrivateAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<EnsureFormDigestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.PowerShell.Commands.Admin.GetTenant.ExecuteCmdlet()
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord()
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.103.1\DSCResources\MSFT_SPOTenantSettings\MSFT_SPOTenantSettings.psm1: line 160
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.103.1\DSCResources\MSFT_SPOTenantSettings\MSFT_SPOTenantSettings.psm1: line 642
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.103.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.103.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 1`
