### ISSUE TITLE
Power Platform extract issue with user or App reg

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoft/Microsoft365DSC#3827]
Hello,

I have a user DSCReport.service@"Company".be in the tenant "group".onmicrosoft.com. Since the latest version (1.23.1018.1) I cannot get the Power Platform extract.

[2/3] Extracting [PPTenantIsolationSettings] using {Credentials}... Error Log created at {file://C:/IO Collaboration/7456-M365DSC-ErrorLog.log}
❌
Please find the different errors and changes I have done.

Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName  -Components $PPComponents -Credential $UserCredential 
Error in 7456-M365DSC-ErrorLog.log
	[WARNING] We recommend providing the username in the format of <tenant>.onmicrosoft.* for the Credential property.
	 System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'TenantId' because it is an empty string.
	   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
	   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
	   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
	   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
	"Error retrieving data:"
	at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1018.1\DSCResources\MSFT_PPTenantIsolationSettings\MSFT_PPTenantIsolationSettings.psm1: line 87
	at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1018.1\DSCResources\MSFT_PPTenantIsolationSettings\MSFT_PPTenantIsolationSettings.psm1: line 667
	at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1018.1\modules\M365DSCReverse.psm1: line 615
	at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1018.1\modules\M365DSCUtil.psm1: line 1312
	at <ScriptBlock>, C:\IO Collaboration\DSC\DSC_exportConfig.ps1: line 223
	at <ScriptBlock>, <No file>: line 1
	DSCReport.service@"Company".be
	TenantId: "Company".be

 Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName  -Components $PPComponents -Credential $UserCredential **-TenantId $TenantId**
	[WARNING] We recommend providing the username in the format of <tenant>.onmicrosoft.* for the Credential property.
	[ERROR] You have to specify ApplicationId when you specify TenantId
	

 Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName  -Components $PPComponents -Credential $UserCredential -TenantId $TenantId **-ApplicationId $ApplicationId** 
	[WARNING] We recommend providing the username in the format of <tenant>.onmicrosoft.* for the Credential property.
	[ERROR] You have to specify ApplicationSecret, CertificateThumbprint or CertificatePath when you specify ApplicationId/TenantId
	

 Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName  -Components $PPComponents -Credential $UserCredential -TenantId $TenantId -ApplicationId $ApplicationId **-CertificateThumbprint $CertificateThumbprint**
	[WARNING] We recommend providing the username in the format of <tenant>.onmicrosoft.* for the Credential property.
	Exporting Microsoft 365 configuration for Components: PPPowerAppsEnvironment, PPTenantIsolationSettings, PPTenantSettings
	
	Authentication methods specified:
	- CredentialsWithApplicationId
	- Service Principal with Certificate Thumbprint

	Connect-MgGraph : ClientCertificateCredential authentication failed: Could not load type 'Microsoft.Identity.Client.Extensibility.AppTokenProviderPara
	meters' from assembly 'Microsoft.Identity.Client, Version=4.36.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'.
	At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.121\Workloads\MicrosoftGraph.psm1:111 char:21
	+ ...             Connect-MgGraph -ClientId $Global:MSCloudLoginConnectionP ...
	+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], AuthenticationFailedException
	    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph

Is it possible to add the tenantId with Credential without ApplicationID and CertificateThumbprint?
Or is there another solution?

Thanks

**Comment by OlivierWaterloos** [comment]
I have uninstall the latest version, and install the version 1.23.201.1 and it's working fine.

**Comment by OlivierWaterloos** [comment]
Hello,
I do not agree to close this issue. 
As workaround we can install the 1.23.201.1, but it is not working with the 1.23.1018.1.

**Comment by OlivierWaterloos** [comment]
Hello,

Can you tell me when will it be resolved?

Thanks

**Comment by FabienTschanz** [comment]
@OlivierWaterloos The logic with Power Platform was updated. Please check if it's resolved.
