### ISSUE TITLE
Issue in extracting O356OrgSettings. Need help to get it fixed. 

### ISSUE THREAD

**Issue by RajeshNarayanamoorthy10** [microsoft/Microsoft365DSC#3864]
Error message - {InvalidOperation} System.Net.WebException: The remote server returned an error: (400) Bad Request.    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() "Error during Export:"

```[tasklist]
### Tasks
```

**Comment by andikrueger** [comment]
Could you please elaborate a bit more with some steps on how to repo this issue? Thanks!

**Comment by RajeshNarayanamoorthy10** [comment]
Trying to export the current configurations. For Office 365, when using the below code generated in https://export.microsoft365dsc.com/, getting the error mentioned.

Code Used :
$Credential = Get-Credential
Export-M365DSCConfiguration -Components @("O365AdminAuditLogConfig", "O365OrgCustomizationSetting", "O365OrgSettings", "O365SearchAndIntelligenceConfigurations") -Credential $Credential

Error: 
Error Log created at {file://C:/WINDOWS/system32/10712-M365DSC-ErrorLog.log

{InvalidOperation}
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
"Error during Export:"

**Comment by andikrueger** [comment]
This looks like an issue with your outgoing network settings. Are you behind a proxy?

Could you try to run this within a PS Session:

Invoke-WebRequest -URI https://www.microsoft365dsc.com

This should return the M365DSC website.

**Comment by RajeshNarayanamoorthy10** [comment]
No Andi. I am not behind a proxy.
I did the test suggested and it is returning the website.

**Comment by andikrueger** [comment]
Could you please share the ErrorLog file - Please redact any sensitive information.

**Comment by RajeshNarayanamoorthy10** [comment]
[M365DSCErrorLog.log](https://github.com/microsoft/Microsoft365DSC/files/13280129/M365DSCErrorLog.log)
I have attached the error log file.

**Comment by RajeshNarayanamoorthy10** [comment]
Andi, did you get a chance to check the error log file ?

**Comment by FabienTschanz** [comment]
@RajeshNarayanamoorthy10 Did you get it working? Can we close the issue or do you require further assistance?

**Comment by FabienTschanz** [comment]
Closing the issue for now. If required, feel free to reopen it.
