### ISSUE TITLE
Getting error while exporting SPO Configuration using Service Principle 

### ISSUE THREAD

**Issue by RohitRaj-18** [microsoft/Microsoft365DSC#4171]
### Description of the issue

Hey , I am trying to export the Configuration for SPO Workload However i am getting error as :Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation."

The Azure AD Application does have all the  necessary Graph API Permission and certificate thumbprint in place but still getting the same error. 

Any help/suggestion would be really appreciated. 

Error Code :: 
Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
<img width="460" alt="Capture" src="https://github.com/microsoft/Microsoft365DSC/assets/142396151/256bc4d9-55ba-489a-9d64-0e5f71f255e5">

### Microsoft 365 DSC Version

1.24.110.1 

### Which workloads are affected

SharePoint Online

### The DSC configuration

```powershell
Export-M365DSCConfiguration -Workloads @("SPO") -Mode Full `
                            -ApplicationId $AppID2 -TenantId $TenantID -CertificateThumbprint $CertificateThumbprint2 `
                            -Path ($Path +"\M365Tenant") -FileName M365TenantConfigAll.ps1
```

**Comment by andikrueger** [comment]
Could you try to connect to SharePoint online with PNP PowerShell/MSCloudloginAssistant?

```powershell
Connect-M365Tenant -Workload PnP -Url -ApplicationId $AppID2 -TenantId $TenantID  -CertificateThumbprint $CertificateThumbprint2
Get-PnPTenant
Get-PnPException
```

**Comment by RohitRaj-18** [comment]
Hello @andikrueger I have been able to resolve the error "Microsoft.SharePoint.Client.ServerUnauthorizedAccessException:".

However my concern is that I was trying earlier by giving the below 3 permission to Azure AD Application :

1. Sites.read.All
2. Termstore.Read.All
3. User.Read.All

However once i gave "Sites.Fullcontrol.All". it resulted into a seamless connect with no error. 

Now I am assuming that in order to export the SPO Configuration using SPN (Service Principle), Is it mandatory to give Site.FullControl.All Permission. 

Please help .

**Comment by andikrueger** [comment]
Thanks for the feedback.

Yes, Sites.FullControl.All is a requirement for the application be able to successfully connect to the SPO APIs.

**Comment by RohitRaj-18** [comment]
Hello @andikrueger  I need some more assistance in exporting the "O365OrgSettings" using the code 
Export-M365DSCConfiguration -Components @( "O365OrgSettings") `
                            -ApplicationId $AppID2 -TenantId $TenantID -CertificateThumbprint $CertificateThumbprint2 `
                            -Path ($Path +"\O365") -FileName O365CompConfigAll.ps1 

The permission/role  which has been assigned to the Azure AD App are : 
Global Reader
Security Reader

While exporting the configuration am getting the below error : 

======================================================================
[2024/01/17 03:01:58]
{ProtocolError}
Microsoft.Exchange.Management.RestApiClient.RestClientException: The following authorization requirements are not satisfied: ((TokenTypeAuthorizationRequirement(UserActAs, AppOnly)&ScopeAuthorizationRequirement(OrganizationSettings.Read, OrganizationSettings.ReadWrite, OrganizationSettings.Read, OrganizationSettings.ReadWrite))|WidsAuthorizationRequirement(62e90394-69f5-4237-9190-012177145e10,29232cdf-9323-42fd-ade2-1d097af3e4de,69091246-20e8-4a56-aa4d-066075b2a7a8,eb1f4a8d-243a-41f0-9fbd-c7cdf6c5ef7c)).
   at Microsoft.Exchange.Management.RestApiClient.M365Insights.WeveAdminCmdlet`2.HandleErrorResponse(HttpResponseMessage response, String settingsName)
   at Microsoft.Exchange.Management.RestApiClient.M365Insights.WeveAdminCmdlet`2.MakeAndSendGetRequest[T](String settingsName, Uri uri)
   at Microsoft.Exchange.Management.RestApiClient.Analytics.GetDefaultTenantMyAnalyticsFeatureConfig.InternalProcessRecord()
   at Microsoft.Exchange.Management.RestApiClient.AdminCmdlet`2.<ProcessRecord>b__34_0()
   at Microsoft.Exchange.Management.RestApiClient.AdminCmdlet`2.ExecuteWithExceptionHandling(Action action, Exception& exception)
"Error retrieving data:"
at Get-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\DSCResources\MSFT_O365OrgSettings\MSFT_O365OrgSettings.psm1: line 289
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\DSCResources\MSFT_O365OrgSettings\MSFT_O365OrgSettings.psm1: line 1056
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 2
TenantId: manishr.onmicrosoft.com



[2024/01/17 03:01:58]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Get-M365DSCExportContentForResource(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCUtil.psm1: line 3333
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\DSCResources\MSFT_O365OrgSettings\MSFT_O365OrgSettings.psm1: line 1061
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 2
TenantId: manishr.onmicrosoft.com

**Comment by RohitRaj-18** [comment]
@andikrueger To add on I have already provided "Exchange.AsanApp" permission to the Azure AD Application

**Comment by RohitRaj-18** [comment]
> Thanks for the feedback.
> 
> Yes, Sites.FullControl.All is a requirement for the application be able to successfully connect to the SPO APIs.

Hello @andikrueger  May i know why it need "Sites.FullControl.All" as a requirement. Because in my current scenario we are need to give only Read Access on the Azure AD Application.

**Comment by andikrueger** [comment]
This is a SharePoint Online limitation. There is no other role/permission available that would allow the access of an application to tenant admin information.

**Comment by RohitRaj-18** [comment]
@andikrueger  Does Global Reader or Security Reader Permission helps on fetching the SharePoint Online Configuration using DSC Module. 

The reason being because i removed Sites.FullControl.All permission from the Azure AD App and just kept the 3 basic Read Permission along with the "Global Reader" and "Security Reader". Is it the correct way or i will face trouble in the production environment. 

Sites.read.All
Termstore.Read.All
User.Read.All

**Comment by RohitRaj-18** [comment]
> This is a SharePoint Online limitation. There is no other role/permission available that would allow the access of an application to tenant admin information.

Is this something which recently got updated into the DSC Module or it has been a mandatory for long.

**Comment by FabienTschanz** [comment]
This most likely was mandatory for a longer period of time. I'll be closing this one again as it is a direct requirement.
