### ISSUE TITLE
Export-M365DSCConfiguration for AzureAD components failed

### ISSUE THREAD

**Issue by fqzy826** [microsoft/Microsoft365DSC#4535]
### Description of the issue

Try to export the settings using Export-M365DSCConfiguration. The account has global admin role.

The server has the latest DSC module and update-M365DESDependencies has run

It failed when export AzureAD components, but it is working for exporting SPO components. 

I have Microsoft.Graph.Authentication module Version=2.16 installed, but the export seems looking for the the old version 2.15

### Microsoft 365 DSC Version

1.24.403.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```powershell
$cred = Get-Credential

Export-M365DSCConfiguration -Components @("AADApplication") -Credential $cred -Path C:\Temp\M365DSC\AAD -FileName DSC_AAD.ps1 -ConfigurationName DSC_AAD
```

### Verbose logs showing the problem

```powershell
[2024/04/06 06:07:07]
{NotSpecified}
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=2.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Graph.Beta.PowerShell.Module.<OnCmdletBeginProcessing>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.Beta.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.Beta.PowerShell.Module.<EventHandler>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Module.<Signal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaPolicyAuthorizationPolicy_List.<Microsoft-Graph-Beta-PowerShell-Runtime-IEventListener-Signal>d__86.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaPolicyAuthorizationPolicy_List.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=2.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Graph.Authentication.Core, Version=2.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Graph.Beta.PowerShell.Module.<OnCmdletBeginProcessing>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.Beta.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.Beta.PowerShell.Module.<EventHandler>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Module.<Signal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaPolicyAuthorizationPolicy_List.<Microsoft-Graph-Beta-PowerShell-Runtime-IEventListener-Signal>d__86.MoveNext()
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2022 Datacenter Azure Edition
OsOperatingSystemSKU : 407
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.20348.2227
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.20348.2227
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by ricmestre** [comment]
You cannot have mixed versions of Graph installed, so you need to uninstall 2.16.0 and use M365DSC's current requirement which is 2.15.0.

Or just wait for next week's release which will include 2.16.0.

**Comment by fqzy826** [comment]
Thanks, I got the graph module pre-installed and did not check the DSC requirement.
All good now
