### ISSUE TITLE
TeamsWideOrgSettings not exporting

### ISSUE THREAD

**Issue by Robbie254** [microsoft/Microsoft365DSC#4852]
### Description of the issue

When attempting to export the teams wide org settings from tenants it fails extracting. This is the case for multiple tenants. All other exports of teams is working as expected

### Microsoft 365 DSC Version

1.24.703.1

### Which workloads are affected

Teams

### Verbose logs showing the problem

```powershell
[2024/07/09 09:22:20]
{InvalidArgument}
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'AccessTokens'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.703.1\DSCResources\MSFT_TeamsOrgWideAppSettings\MSFT_TeamsOrgWideAppSettings.psm1: line 212
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.703.1\Modules\M365DSCReverse.psm1: line 682
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.703.1\Modules\M365DSCUtil.psm1: line 1394
at <ScriptBlock>, <No file>: line 1
username@domain.com
TenantId: domain.com
```

**Comment by ricmestre** [comment]
The cmdlets related with ```TeamsWideOrgSettings``` only accept user credentials, they don't work with any other authentication methods.

**Comment by Robbie254** [comment]
Thanks for the reply, user credentials are the only authentication method we have tried with this and it is still not working.
