### ISSUE TITLE
Teams Microsoft.Teams.Policy.Administration.Cmdlets.Providers.PolicyRpException: {"code":"Forbidden","message":"Access Denied.","action":"Provide different credential or request access."}

### ISSUE THREAD

**Issue by arnabdeb-lilly** [microsoft/Microsoft365DSC#5052]
I trying to export the 'Microsoft Teams' configuration using DSC using the certificate thumbprint authentication method. When I try doing that, I am getting the error as highlighted in the subject.

Microsoft.Teams.Policy.Administration.Cmdlets.Providers.PolicyRpException: {"code":"Forbidden","message":"Access Denied.","action":"Provide different credential or request access."}

I have granted the Organization.Read.All Application permission for the client ID that I am using for this.

It only works with the credential option when I try with Global Admin account. Has anyone else encountered this issue or would be aware of the solution?

I have shared the logs for one of the configuration error.

**Comment by arnabdeb-lilly** [comment]
`Microsoft.Teams.Policy.Administration.Cmdlets.Providers.PolicyRpException: {"code":"Forbidden","message":"Access Denied.","action":"Provide different credential or request access."}
   at Microsoft.Teams.Policy.Administration.Cmdlets.Providers.HttpRequestHelper`1.<GetAllAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Teams.Policy.Administration.Cmdlets.Providers.BaseTpmGetCmdlet`1.<>c__DisplayClass8_0.<<ProcessRecord>b__0>d.MoveNext()
"Error during Export:"
at Export-TargetResource, xxxxx\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.731.1\DSCResources\MSFT_TeamsAppPermissionPolicy\MSFT_TeamsAppPermissionPolicy.psm1: line 448
at Start-M365DSCConfigurationExtract, xxxxx\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.731.1\Modules\M365DSCReverse.psm1: line 682
at Export-M365DSCConfiguration, xxxxx\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.731.1\Modules\M365DSCUtil.psm1: line 1394
at <ScriptBlock>, <No file>: line 10
TenantId: xxxxx.onmicrosoft.com`

**Comment by arnabdeb-lilly** [comment]
Posted under Issues as #5053
