### ISSUE TITLE
Export/Import for workloads SharePoint and OneDrive is not working using credentials.

### ISSUE THREAD

**Issue by CovidtheDog2024** [microsoft/Microsoft365DSC#5470]
Hi MVP,
Is there a plan to enable credentials for exporting/importing SharePoint and OneDrive, similar to other workloads?"

Error Log:
System.InvalidOperationException: The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.BeginProcessing()
   at PnP.PowerShell.Commands.PnPWebRetrievalsCmdlet`1.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1120.1\DSCResources\MSFT_SPOUserProfileProperty\MSFT_SPOUserProfileProperty.psm1: line 327
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1120.1\Modules\M365DSCReverse.psm1: line 682
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1120.1\Modules\M365DSCUtil.psm1: line 1460
at <ScriptBlock>, <No file>: line 1

**Comment by ArtemPozharovDNSBelgium** [comment]
I even tried using Certificate Thumbprint, but Microsoft 365 DSC does not recognize the tenant...

**Comment by FabienTschanz** [comment]
There were some fixes in the latest versions of Microsoft365DSC that targeted the context used for authentication against SharePoint. Can you please try again?

**Comment by FabienTschanz** [comment]
Closing for now. If the issue persists, please reopen it.
