### ISSUE TITLE
Export-M365DSCConfiguration - EXO - Crash on [20/43] Extracting [EXOInboundConnector]

### ISSUE THREAD

**Issue by rpl-io** [microsoft/Microsoft365DSC#695]
#### Details of the scenario you tried and the problem that is occurring

When running Export-M365DSCConfiguration the script stops on EXOInboundConnector

[20/43] Extracting [EXOInboundConnector]...
    |---[1/1] Receive from Exclaimer Cloud v2❌ Logging a new Error

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev

**Comment by NikCharlebois** [comment]
If you look at the error log (generated in the folder where the command was executed from) what is the error?

**Comment by nlangsto** [comment]
Im getting similar too but for 

[13/101] Extracting [EXOAvailabilityAddressSpace]...
    |---[1/1] dxxxxxo.nxxxxxxxxo.co.uk❌ Logging a new Error

Installed dev branch today 2nd sept.

[2020/09/02 08:08:13]
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'ResourceName' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
""

**Comment by NikCharlebois** [comment]
Can you confirm that this is still happening with the latest version 1.21.630.1 or greater? Thanks
