### ISSUE TITLE
EXOAvailabilityAddressSpace

### ISSUE THREAD

**Issue by nlangsto** [microsoft/Microsoft365DSC#713]
## Details of the scenario you tried and the problem that is occurring
Simple extract using GUI with default settings

#### Verbose logs showing the problem

[13/103] Extracting [EXOAvailabilityAddressSpace]...
    |---[1/1] domxxxxxxxxxxxnco.co.uk❌ Logging a new Error

[2020/07/28 02:35:25]
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'ResourceName' because it is an empty string.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
""

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Export-M365DSCConfiguration

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev
and latest 1.20.723.1
and
1.20.603.1
1.20.716.1

Same applies if I remove EXOAvailabilityAddressSpace from the GUI to try and bypass

[13/102] Extracting [EXOAvailabilityConfig]...❌ Logging a new Error
PS C:\a_dsc>

[2020/07/28 02:51:15]
{InvalidOperation}
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
""

**Comment by NikCharlebois** [comment]
@nglangsto I am not able to replicate the issue. Using 1.20.902.1, I tried:

1 - launch a brand new PoSh Console
2 - Run Export-M365DSCConfiguration
3 - Unselect everything BUT EXOAvailabilityAddressSpace
4 - Provide username and Password and click Start Extraction.

My account is a global admin without MFA. Can you confirm that the steps above give you the error?
