### ISSUE TITLE
Error in Export at 47 Intuneconffig

### ISSUE THREAD

**Issue by wiemerr** [microsoft/Microsoft365DSC#824]
I am seeing this error during export.  I am not finding any reference to this cmdlet via Google/Bing.

System.Management.Automation.CommandNotFoundException: The term 'Connect-MSCloudLoginIntune'

The export stops on this error.

Randy
System.Management.Automation.CommandNotFoundException: The term 'Connect-MSCloudLoginIntune' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Test-MSCloudLogin(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by NikCharlebois** [comment]
@wiemerr what version of MSCloudLoginAssistant are you running? Run:

Get-Module MSCloudLoginAssistant -ListAvailable | select Version

**Comment by NikCharlebois** [comment]
Actually, we've just released an out-of-band version (1.20.1016.1). I'd recommend you try that version and see if it fixes your issue.
