### ISSUE TITLE
Export-M365DSCConfiguration: fails on TeamsTenantDialPlan,TeamsUpgradePolicy,TeamsVoiceRoutingPolicy

### ISSUE THREAD

**Issue by TuomasPakkanen** [microsoft/Microsoft365DSC#828]
#### Details of the scenario you tried and the problem that is occurring

Trying to run the export of the tenant configuration with default settings, but the Teams part fails for TeamsTenantDialPlan,TeamsUpgradePolicy,TeamsVoiceRoutingPolicy options.

#### Verbose logs showing the problem

[2020/10/13 10:05:28]
{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "SourceExists" with "1" argument(s): "The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security, State." ---> System.Security.SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security, State.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at CallSite.Target(Closure , CallSite , Type , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
""

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
This has been fixed in the Log Engine in a previous release.
