### ISSUE TITLE
Error while extracting ODSettings

### ISSUE THREAD

**Issue by hapklaar** [microsoft/Microsoft365DSC#852]
It seems the tool assumes a sharepoint.us FQDN for sharepoint settings. This is not true for Europe I guess, our remote hostname ends with sharepoint.com.

```
[2020-10-21 04:04:46]
{NotSpecified}
System.Net.WebException: The remote name could not be resolved: 'tenantname-admin.sharepoint.us'
   at PnP.PowerShell.Commands.Base.ConnectOnline.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
"Could not initiate the ReverseDSC Extraction"
at Connect-MSCloudLoginPnP, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.41\Workloads\PnP.psm1: line 137
at Test-MSCloudLogin, C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.41\MSCloudLoginAssistant.psm1: line 142
at New-M365DSCConnection, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCUtil.psm1: line 1044
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\DSCResources\MSFT_ODSettings\MSFT_ODSettings.psm1: line 555
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCReverse.psm1: line 467
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCReverseGUI.psm1: line 790
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCReverseGUI.psm1: line 748
at Show-M365DSCGUI, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCReverseGUI.psm1: line 828
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1016.1\modules\M365DSCUtil.psm1: line 863
at <ScriptBlock>, <No file>: line 1
```

**Comment by NikCharlebois** [comment]
This has been fixed with a recent release of MSCloudLoginAssistant
